<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Contrax Home Gutenvese About', 'contrax-lite' ),
	'categories' => array( 'contrax-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"elementId":"guten-GVv1r3","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"gv-color-whitee"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","right":"","bottom":"0","left":""}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"10","bottom":"","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"80","right":"10","bottom":"0","left":"10"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-laLUs5","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-cVZgV9"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"elementId":"guten-kyNP3g","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-qbD4Cx","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"24"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-ARYghK","verticalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]}} -->
<!-- wp:gutenverse/divider {"elementId":"guten-oeM73Z","width":{"Desktop":"100","Mobile":""},"dividerColor":{"type":"variable","id":"gv-color-accent"},"size":{"Desktop":"1"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Mobile":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"70","unit":"px"},"Mobile":{"point":"50","unit":"px"},"Tablet":{"point":"60","unit":"px"}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-RviCKv","content":"About","color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"point":"151","unit":"px"}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-dLQ5X8","content":"Building a Legacy of Excellence","type":3,"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"},"Tablet":{"point":"40","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"uppercase"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"delay":100},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"570","unit":"px"},"Tablet":{"point":"394","unit":"px"},"Mobile":{"point":"280","unit":"px"}}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"elementId":"guten-n7u8ma","verticalAlign":{"Desktop":"flex-end","Tablet":"flex-end"},"horizontalAlign":{"Desktop":"flex-end","Tablet":"flex-start","Mobile":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"15"}}},"animation":{"type":{"Desktop":"fadeInRight"},"delay":300}} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-gL2gvj","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"440","unit":"px"},"Tablet":{"point":"465","unit":"px"}}} -->
<!-- wp:paragraph -->
<p>Signifies our commitment to surpassing industry standards through attention to detail, innovation, and integrity, shaping the future with quality.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-SuIYrF","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-siku2Q","background":{"type":"default","image":{"Desktop":{"id":108,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/work-architecture-structure-window-glass-building-new.webp","width":1920,"height":710,"altOriginal":"work architecture structure window"},"Mobile":{"id":133,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/work-architecture-structure-window-glass-building-mobile.jpg"},"Tablet":{"id":108,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/work-architecture-structure-window-glass-building-new.jpg"}},"position":{"Desktop":"bottom center","Tablet":"center right","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover","Tablet":"cover"},"xposition":{"Tablet":{"point":"-300","unit":"px"},"Mobile":{"point":"-860","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-text-primaryy"}},"opacity":"0.1","margin":{"Mobile":{"unit":"px","dimension":{"left":""}},"Desktop":[]},"padding":{"Mobile":{"unit":"px","dimension":{"right":""}},"Desktop":[]}} -->
<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-PxudVG","background":{"videoPlayOnMobile":false,"type":"gradient","color":{"r":252,"g":96,"b":46,"a":1},"gradientColor":[{"color":"rgba(252, 96, 46, 0)","active":false,"opacity":0,"id":4,"offset":"0.067"},{"color":"rgba(252, 96, 46, 1)","active":false,"opacity":1,"id":1,"offset":"0.069"},{"color":"rgba(252, 96, 46, 1)","active":true,"opacity":1,"id":2,"offset":"0.922"},{"color":"rgba(252, 96, 46, 0)","active":false,"opacity":0,"id":3,"offset":"0.924"}],"gradientType":"linear","gradientAngle":"225"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10","top":"10","bottom":"10"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"zIndex":{"Desktop":2},"animation":{"type":{"Desktop":"fadeInLeft"},"delay":300},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"423","unit":"px"},"Tablet":{"point":"370","unit":"px"},"Mobile":{"point":"308","unit":"px"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"0","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"unit":"px"}},"mask":{"shape":"","svg":{"id":261,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/shape-mask.png"},"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"},"position":{"Desktop":"center center"}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-HnB359","background":{"type":"default","color":""},"verticalAlign":{"Desktop":"default","Tablet":"default"},"horizontalAlign":{"Desktop":"flex-end","Tablet":"flex-end","Mobile":"flex-end"},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"30","top":"40","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"40","left":"30"}}},"mask":{"shape":"","svg":[],"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-tWiw9j","content":"Cart Growth Insights","type":3,"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-feature-alt-primary","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"600","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"170","unit":"px"},"Mobile":{"point":"180","unit":"px"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"30","unit":"px"}},"positioningTop":{"Tablet":{"point":"20","unit":"px"},"Desktop":{"point":"30","unit":"px"}}} /-->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-xa3BT6","margin":{"Desktop":{"unit":"px","dimension":{"right":"","bottom":"","top":"40","left":""}},"Mobile":{"unit":"px","dimension":{"top":"100","right":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"150","unit":"px"},"Mobile":{"point":"95","unit":"px"}},"positioningLocation":"default","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":100},"elementId":"guten-OPaHqS","verticalAlign":{"Desktop":"default","Tablet":"flex-end"},"horizontalAlign":{"Desktop":"flex-end"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]}} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-5mkhdT","iconType":"none","iconColor":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"iconSize":{"Desktop":""},"iconPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"prefix":"","number":"55","safeNumber":"55","suffix":"","title":"Increase in Retention","showSupper":true,"supper":"%","superColor":{"type":"variable","id":"gv-color-white"},"superTypography":{"type":"variable","id":"gv-font-primary-alt-secondary","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"superTop":{"Desktop":"-2","Mobile":"0"},"superSpace":{"Desktop":"-3","Mobile":"-5"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"left","Tablet":"left"},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-white"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-white"}},"numberTypography":{"type":"variable","id":"gv-font-primary-alt-secondary","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"titleTypography":{"type":"variable","id":"gv-font-text-small","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"numberBottomSpace":{"Desktop":"-2","Mobile":"4","Tablet":-5},"titleBottomSpace":{"Mobile":"","Desktop":"","Tablet":null},"numberRightSpace":{"Desktop":"","Tablet":null},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"default","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"160","unit":"px"},"Mobile":{"unit":"%","point":"50"}},"positioningLocation":"default","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}},"imageLoad":"eager"} /-->

<!-- wp:gutenverse/fun-fact {"elementId":"guten-Cf9a7Y","iconType":"none","iconColor":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"iconSize":{"Desktop":""},"iconPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"prefix":"","number":"65","safeNumber":"65","suffix":"","title":"Increase Cart Growth","showSupper":true,"supper":"%","superColor":{"type":"variable","id":"gv-color-white"},"superTypography":{"type":"variable","id":"gv-font-primary-alt-secondary","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"superTop":{"Desktop":"-2","Mobile":"0"},"superSpace":{"Desktop":"-3","Mobile":"-5"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"left","Tablet":"left"},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-white"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-white"}},"numberTypography":{"type":"variable","id":"gv-font-primary-alt-secondary","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"titleTypography":{"type":"variable","id":"gv-font-text-small","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"numberBottomSpace":{"Desktop":"-2","Mobile":"4","Tablet":-5},"titleBottomSpace":{"Mobile":"","Desktop":"","Tablet":null},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"default","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"160","unit":"px"},"Mobile":{"unit":"%","point":"50"}},"positioningLocation":"default","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/spacer {"elementId":"guten-wtcQpn","space":{"Desktop":{"point":"435","unit":"px"},"Tablet":{"point":"410","unit":"px"},"Mobile":{"point":"500","unit":"px"}},"borderResponsive":{"Mobile":{"radius":[]}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
