<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Contrax Home Gutenvese About', 'contrax-lite' ),
	'categories' => array( 'contrax-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"elementId":"guten-GVv1r3","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","right":"","bottom":"0","left":""}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"10","bottom":"","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"80","right":"10","bottom":"0","left":"10"}}}} -->
<div class="section-wrapper" data-id="GVv1r3"><section class="wp-block-gutenverse-section guten-element guten-section guten-GVv1r3 layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-laLUs5","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-laLUs5"><div class="guten-column-wrapper" data-id="laLUs5"><!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-cVZgV9"} -->
<div class="section-wrapper" data-id="cVZgV9"><section class="wp-block-gutenverse-section guten-element guten-section guten-cVZgV9 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"elementId":"guten-kyNP3g","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-kyNP3g"><div class="guten-column-wrapper" data-id="kyNP3g"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-qbD4Cx","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"24"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"}}} -->
<div class="section-wrapper" data-id="qbD4Cx"><section class="wp-block-gutenverse-section guten-element guten-section guten-qbD4Cx animated guten-element-hide desktop-fadeInLeft layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-ARYghK","verticalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ARYghK"><div class="guten-column-wrapper" data-id="ARYghK"><!-- wp:gutenverse/divider {"elementId":"guten-oeM73Z","width":{"Desktop":"100","Mobile":""},"dividerColor":{"type":"variable","id":"theme-2"},"size":{"Desktop":"1"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Mobile":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"70","unit":"px"},"Mobile":{"point":"50","unit":"px"},"Tablet":{"point":"60","unit":"px"}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-oeM73Z"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/heading {"elementId":"guten-RviCKv","type":6,"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"n1CZUD","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"point":"151","unit":"px"}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-RviCKv">About</h6>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-dLQ5X8","color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"iIJ9h6","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"},"Tablet":{"point":"40","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"uppercase"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"delay":100},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"570","unit":"px"},"Tablet":{"point":"394","unit":"px"},"Mobile":{"point":"280","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-dLQ5X8 animated guten-element-hide desktop-fadeInLeft">Building a Legacy of Excellence</h2>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"elementId":"guten-n7u8ma","verticalAlign":{"Desktop":"flex-end","Tablet":"flex-end"},"horizontalAlign":{"Desktop":"flex-end","Tablet":"flex-start","Mobile":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"15"}}},"animation":{"type":{"Desktop":"fadeInRight"},"delay":300}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-n7u8ma animated guten-element-hide desktop-fadeInRight"><div class="guten-column-wrapper" data-id="n7u8ma"><!-- wp:gutenverse/text-editor {"elementId":"guten-gL2gvj","textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"k9LI1q","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"440","unit":"px"},"Tablet":{"point":"465","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-gL2gvj"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Signifies our commitment to surpassing industry standards through attention to detail, innovation, and integrity, shaping the future with quality.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-SuIYrF","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="SuIYrF"><section class="wp-block-gutenverse-section guten-element guten-section guten-SuIYrF layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-siku2Q","background":{"type":"default","image":{"Desktop":{"id":108,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/work-architecture-structure-window-glass-building-new.jpg"},"Mobile":{"id":133,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/work-architecture-structure-window-glass-building-mobile.jpg"},"Tablet":{"id":108,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/work-architecture-structure-window-glass-building-new.jpg"}},"position":{"Desktop":"bottom center","Tablet":"center right","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover","Tablet":"cover"},"xposition":{"Tablet":{"point":"-300","unit":"px"},"Mobile":{"point":"-860","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-0"}},"opacity":"0.1","margin":{"Mobile":{"unit":"px","dimension":{"left":""}},"Desktop":[]},"padding":{"Mobile":{"unit":"px","dimension":{"right":""}},"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-siku2Q"><div class="guten-column-wrapper" data-id="siku2Q"><div class="guten-background-overlay"></div><!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-PxudVG","background":{"videoPlayOnMobile":false,"type":"gradient","color":{"r":252,"g":96,"b":46,"a":1},"gradientColor":[{"color":"rgba(252, 96, 46, 0)","active":false,"opacity":0,"id":4,"offset":"0.067"},{"color":"rgba(252, 96, 46, 1)","active":false,"opacity":1,"id":1,"offset":"0.069"},{"color":"rgba(252, 96, 46, 1)","active":true,"opacity":1,"id":2,"offset":"0.922"},{"color":"rgba(252, 96, 46, 0)","active":false,"opacity":0,"id":3,"offset":"0.924"}],"gradientType":"linear","gradientAngle":"225"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10","top":"10","bottom":"10"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"zIndex":{"Desktop":2},"animation":{"type":{"Desktop":"fadeInLeft"},"delay":300},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"423","unit":"px"},"Tablet":{"point":"370","unit":"px"},"Mobile":{"point":"308","unit":"px"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"0","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"0","unit":"px"}},"mask":{"shape":"","svg":{"id":261,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/shape-mask.png"},"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"},"position":{"Desktop":"center center"}}} -->
<div class="section-wrapper" data-id="PxudVG"><section class="wp-block-gutenverse-section guten-element guten-section guten-PxudVG animated guten-element-hide desktop-fadeInLeft layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-HnB359","background":{"type":"default","color":""},"verticalAlign":{"Desktop":"default","Tablet":"default"},"horizontalAlign":{"Desktop":"flex-end","Tablet":"flex-end","Mobile":"flex-end"},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"30","top":"40","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"40","left":"30"}}},"mask":{"shape":"","svg":[],"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-HnB359"><div class="guten-column-wrapper" data-id="HnB359"><!-- wp:gutenverse/heading {"elementId":"guten-tWiw9j","type":5,"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"z5lRfr","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"600","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"170","unit":"px"},"Mobile":{"point":"180","unit":"px"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"30","unit":"px"}},"positioningTop":{"Tablet":{"point":"20","unit":"px"},"Desktop":{"point":"30","unit":"px"}}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-tWiw9j">Cart Growth Insights</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-xa3BT6","margin":{"Desktop":{"unit":"px","dimension":{"right":"","bottom":"","top":"40","left":""}},"Mobile":{"unit":"px","dimension":{"top":"100","right":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"140","unit":"px"},"Mobile":{"point":"95","unit":"px"}},"positioningLocation":"default","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}}} -->
<div class="section-wrapper" data-id="xa3BT6"><section class="wp-block-gutenverse-section guten-element guten-section guten-xa3BT6 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":100},"elementId":"guten-OPaHqS","verticalAlign":{"Desktop":"default","Tablet":"flex-end"},"horizontalAlign":{"Desktop":"flex-end"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-OPaHqS"><div class="guten-column-wrapper" data-id="OPaHqS"><!-- wp:gutenverse/fun-fact {"elementId":"guten-5mkhdT","iconType":"none","iconColor":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"iconSize":{"Desktop":""},"iconPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"prefix":"","number":"55","suffix":"","title":"Increase in Retention","showSupper":true,"supper":"%","superColor":{"type":"variable","id":"kvOUbD"},"superTypography":{"type":"variable","id":"L2uoM8","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"42","unit":"px"},"Tablet":{"point":"42","unit":"px"},"Mobile":{"point":"35","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"700"},"superTop":{"Desktop":"-2","Mobile":"0"},"superSpace":{"Desktop":"-3","Mobile":"-5"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"left","Tablet":"left"},"numberColor":{"Desktop":{"type":"variable","id":"theme-1"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-1"}},"numberTypography":{"type":"variable","id":"aRqp9G","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"45","unit":"px"},"Mobile":{"point":"35","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"titleTypography":{"type":"variable","id":"owa82Y","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"400"},"numberBottomSpace":{"Desktop":"0","Mobile":"4","Tablet":-5},"titleBottomSpace":{"Mobile":"","Desktop":"","Tablet":null},"numberRightSpace":{"Desktop":"","Tablet":null},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"default","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"160","unit":"px"},"Mobile":{"unit":"%","point":"50"}},"positioningLocation":"default","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}}} -->
<div class="guten-element guten-5mkhdT guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="55" data-duration="3500"></span><span class="suffix"></span><sup class="super">%</sup></div><span class="title">Increase in Retention</span></div></div></div>
<!-- /wp:gutenverse/fun-fact -->

<!-- wp:gutenverse/fun-fact {"elementId":"guten-Cf9a7Y","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"iconSize":{"Desktop":""},"iconPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"prefix":"","number":"65","suffix":"","title":"Increase Cart Growth","showSupper":true,"supper":"%","superColor":{"type":"variable","id":"kvOUbD"},"superTypography":{"type":"variable","id":"L2uoM8","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"42","unit":"px"},"Tablet":{"point":"42","unit":"px"},"Mobile":{"point":"35","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"700"},"superTop":{"Desktop":"-2","Mobile":"0"},"superSpace":{"Desktop":"-3","Mobile":"-5"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"left","Tablet":"left"},"numberColor":{"Desktop":{"type":"variable","id":"theme-1"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-1"}},"numberTypography":{"type":"variable","id":"aRqp9G","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"45","unit":"px"},"Mobile":{"point":"35","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"titleTypography":{"type":"variable","id":"owa82Y","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"400"},"numberBottomSpace":{"Desktop":"0","Mobile":"4","Tablet":-5},"titleBottomSpace":{"Mobile":"","Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"00","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"default","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"160","unit":"px"},"Mobile":{"unit":"%","point":"50"}},"positioningLocation":"default","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}}} -->
<div class="guten-element guten-Cf9a7Y guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="65" data-duration="3500"></span><span class="suffix"></span><sup class="super">%</sup></div><span class="title">Increase Cart Growth</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/spacer {"elementId":"guten-wtcQpn","space":{"Desktop":{"point":"435","unit":"px"},"Tablet":{"point":"410","unit":"px"},"Mobile":{"point":"500","unit":"px"}},"borderResponsive":{"Mobile":{"radius":[]}}} -->
<div class="guten-element guten-spacer guten-wtcQpn"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
