<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Contrax Single Gutenvese Hero', 'contrax-lite' ),
	'categories' => array( 'contrax-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1290"},"gap":"no","elementId":"guten-OVNz1Q","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":235,"g":235,"b":235,"a":1},"image":{"Desktop":[],"Tablet":[]},"position":{"Desktop":"center right","Mobile":"center center","Tablet":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain","Mobile":"cover"},"xposition":{"Desktop":{"point":"1","unit":"px"},"Mobile":{"point":"-500","unit":"px"},"Tablet":{"point":"-450","unit":"px"}},"width":{"Desktop":{"point":"1800","unit":"px"},"Mobile":{"unit":"px","point":"1200"}},"yposition":{"Mobile":{"point":"","unit":"px"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"mask":{"shape":"","svg":[],"size":{"Desktop":"custom"},"position":{"Desktop":"top right"},"repeat":{"Desktop":"no-repeat"},"scale":{"Desktop":{"unit":"%","point":"100"}}}} -->
<div class="section-wrapper" data-id="OVNz1Q"><section class="wp-block-gutenverse-section guten-element guten-section guten-OVNz1Q layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-nLVg08","opacity":"","horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-nLVg08"><div class="guten-column-wrapper" data-id="nLVg08"><!-- wp:gutenverse/spacer {"elementId":"guten-lfDSBb","space":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Tablet":{"radius":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":null},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"positioningLocation":"absolute","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningTop":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"","unit":"px"}},"mask":{"shape":"custom","svg":{"id":61,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/masking.png"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"theme-1"}}} -->
<div class="guten-element guten-spacer guten-lfDSBb"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-kZZQPa","margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"","bottom":"100","left":""}},"Mobile":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}}}} -->
<div class="section-wrapper" data-id="kZZQPa"><section class="wp-block-gutenverse-section guten-element guten-section guten-kZZQPa layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-QofTu2","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-QofTu2"><div class="guten-column-wrapper" data-id="QofTu2"><!-- wp:gutenverse/post-title {"elementId":"guten-LsiluZ","htmlTag":"h2","alignment":{"Tablet":"center","Desktop":"center","Mobile":"center"},"typography":{"type":"variable","id":"iIJ9h6","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"},"Tablet":{"point":"40","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"uppercase"},"color":{"type":"variable","id":"theme-0"},"borderResponsive":{"Tablet":{"radius":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"1000","unit":"px"}}} -->
<div class="guten-element guten-post-title guten-LsiluZ"></div>
<!-- /wp:gutenverse/post-title -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-1h5yZZ","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<div class="section-wrapper" data-id="1h5yZZ"><section class="wp-block-gutenverse-section guten-element guten-section guten-1h5yZZ layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-q7dKAR","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-q7dKAR"><div class="guten-column-wrapper" data-id="q7dKAR"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Wf6uZq","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5","right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"}} -->
<div class="section-wrapper" data-id="Wf6uZq"><section class="wp-block-gutenverse-section guten-element guten-section guten-Wf6uZq layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-mkDtAf"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-mkDtAf"><div class="guten-column-wrapper" data-id="mkDtAf"><!-- wp:gutenverse/icon {"elementId":"guten-1OzA7A","icon":"fas fa-user","iconAlign":{"Tablet":"center"},"iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"},"Tablet":{"point":"","unit":"px"}},"iconPadding":{"Desktop":"0","Mobile":"","Tablet":"0"},"iconRotate":{"Tablet":""},"iconColorTwo":{"type":"variable","id":"theme-2"},"iconShape":"circle","margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"1","right":"10","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-1OzA7A guten-icon"><span class="guten-icon-wrapper circle stacked"><i class="fas fa-user"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/post-author {"elementId":"guten-Vz0U8S","authorAvatar":false,"typography":{"type":"variable","id":"pDlWqy","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"color":{"type":"variable","id":"theme-0"},"authorBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-post-author guten-Vz0U8S"></div>
<!-- /wp:gutenverse/post-author --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-eh85QY","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"right":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}},"left":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"borderResponsive":{"Mobile":{"radius":[],"left":{"type":"none"},"right":{"type":"none"}}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20","left":"20","top":"5","bottom":"5"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"}} -->
<div class="section-wrapper" data-id="eh85QY"><section class="wp-block-gutenverse-section guten-element guten-section guten-eh85QY layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-uNFaO1","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-uNFaO1"><div class="guten-column-wrapper" data-id="uNFaO1"><!-- wp:gutenverse/icon {"elementId":"guten-bsRfdF","icon":"fas fa-calendar-alt","iconAlign":{"Tablet":"center"},"iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"},"Tablet":{"point":"","unit":"px"}},"iconPadding":{"Desktop":"0","Mobile":"","Tablet":"0"},"iconRotate":{"Tablet":""},"iconColorTwo":{"type":"variable","id":"theme-2"},"iconShape":"circle","margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"1","right":"10","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-bsRfdF guten-icon"><span class="guten-icon-wrapper circle stacked"><i class="fas fa-calendar-alt"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/post-date {"elementId":"guten-oA83Zp","typography":{"type":"variable","id":"pDlWqy","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"color":{"type":"variable","id":"theme-0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0"}},"Mobile":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-post-date guten-oA83Zp"></div>
<!-- /wp:gutenverse/post-date --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-XIyhay","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline","Mobile":"full"}} -->
<div class="section-wrapper" data-id="XIyhay"><section class="wp-block-gutenverse-section guten-element guten-section guten-XIyhay layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-nfe4t1","horizontalAlign":{"Desktop":"default","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-nfe4t1"><div class="guten-column-wrapper" data-id="nfe4t1"><!-- wp:gutenverse/icon {"elementId":"guten-KZFeo3","icon":"fas fa-folder-open","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0","Mobile":"0","Tablet":"0"},"iconColorTwo":{"type":"variable","id":"theme-2"},"iconShape":"circle","hideMobile":false,"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Tablet":{"unit":"px","dimension":{"top":"3","right":"10","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-KZFeo3 guten-icon"><span class="guten-icon-wrapper circle stacked"><i class="fas fa-folder-open"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/post-terms {"elementId":"guten-PTuL6z","linkTo":"term","typography":{"type":"variable","id":"pDlWqy","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"color":{"type":"variable","id":"theme-0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":""}}},"padding":{"Desktop":[]},"hideMobile":false,"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-post-terms guten-PTuL6z"></div>
<!-- /wp:gutenverse/post-terms --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/spacer {"elementId":"guten-Co4K5D","space":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":1},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"0","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}},"mask":{"shape":"custom","svg":{"id":62,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/masking-alt.png"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"theme-1"}}} -->
<div class="guten-element guten-spacer guten-Co4K5D"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
