<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Contrax Blog Gutenvese Hero', 'contrax-lite' ),
	'categories' => array( 'contrax-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1290"},"gap":"no","elementId":"guten-OVNz1Q","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":235,"g":235,"b":235,"a":1},"image":{"Desktop":[],"Tablet":[]},"position":{"Desktop":"center right","Mobile":"center center","Tablet":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain","Mobile":"cover"},"xposition":{"Desktop":{"point":"1","unit":"px"},"Mobile":{"point":"-500","unit":"px"},"Tablet":{"point":"-450","unit":"px"}},"width":{"Desktop":{"point":"1800","unit":"px"},"Mobile":{"unit":"px","point":"1200"}},"yposition":{"Mobile":{"point":"","unit":"px"}}},"backgroundOverlay":{"type":"default","gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":6,"offset":"0.048"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":5,"offset":"0.049"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":4,"offset":"0.951"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"0.951"}],"gradientType":"linear","gradientAngle":"225"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"mask":{"shape":"","svg":[],"size":{"Desktop":"custom"},"position":{"Desktop":"top right"},"repeat":{"Desktop":"no-repeat"},"scale":{"Desktop":{"unit":"%","point":"100"}}}} -->
<div class="section-wrapper" data-id="OVNz1Q"><section class="wp-block-gutenverse-section guten-element guten-section guten-OVNz1Q layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-nLVg08","opacity":"","horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-nLVg08"><div class="guten-column-wrapper" data-id="nLVg08"><!-- wp:gutenverse/spacer {"elementId":"guten-lfDSBb","space":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Tablet":{"radius":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":null},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"positioningLocation":"absolute","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningTop":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"","unit":"px"}},"mask":{"shape":"custom","svg":{"id":61,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/masking.png"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"theme-1"}}} -->
<div class="guten-element guten-spacer guten-lfDSBb"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-kZZQPa","margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"","bottom":"100","left":""}},"Mobile":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}}}} -->
<div class="section-wrapper" data-id="kZZQPa"><section class="wp-block-gutenverse-section guten-element guten-section guten-kZZQPa layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-QofTu2","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-QofTu2"><div class="guten-column-wrapper" data-id="QofTu2"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-gFhiLO","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"24"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"animation":{"type":{"Desktop":"fadeInUp"}}} -->
<div class="section-wrapper" data-id="gFhiLO"><section class="wp-block-gutenverse-section guten-element guten-section guten-gFhiLO animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-PyLMXW","verticalAlign":{"Desktop":"default","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-PyLMXW"><div class="guten-column-wrapper" data-id="PyLMXW"><!-- wp:gutenverse/divider {"elementId":"guten-ixNi9G","width":{"Desktop":"100","Mobile":"100"},"dividerColor":{"type":"variable","id":"theme-2"},"size":{"Desktop":"1"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"custom","Mobile":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"70","unit":"px"},"Mobile":{"point":"40","unit":"px"},"Tablet":{"point":"60","unit":"px"}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-ixNi9G"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/heading {"elementId":"guten-Ay4rw3","type":6,"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"n1CZUD","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"15","left":"15"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"point":"151","unit":"px"}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-Ay4rw3">Our Blog</h6>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/divider {"elementId":"guten-NxVf3u","width":{"Desktop":"100","Mobile":""},"dividerColor":{"type":"variable","id":"theme-2"},"size":{"Desktop":"1"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"hideMobile":false,"positioningType":{"Desktop":"custom","Mobile":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"70","unit":"px"},"Mobile":{"point":"40","unit":"px"},"Tablet":{"point":"60","unit":"px"}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-NxVf3u"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-kQjWjL","type":1,"textAlign":{"Tablet":"center","Desktop":"center","Mobile":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"7BXnGM","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"50","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"10","right":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInDown"},"delay":200}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-kQjWjL animated guten-element-hide desktop-fadeInDown">Blogs & Articles</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-d7F5jd","alignment":{"Desktop":"center","Mobile":"center"},"textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"k9LI1q","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}},"animation":{"type":{"Desktop":"fadeInDown"},"delay":300},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"590","unit":"px"},"Tablet":{"point":"500","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-d7F5jd animated guten-element-hide desktop-fadeInDown"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/spacer {"elementId":"guten-Co4K5D","space":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":1},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"0","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}},"mask":{"shape":"custom","svg":{"id":62,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/masking-alt.png"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"theme-1"}}} -->
<div class="guten-element guten-spacer guten-Co4K5D"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
