<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Contrax Single Gutenvese Hero', 'contrax-lite' ),
	'categories' => array( 'contrax-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1290"},"gap":"no","elementId":"guten-OVNz1Q","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":235,"g":235,"b":235,"a":1},"image":{"Desktop":[],"Tablet":[]},"position":{"Desktop":"center right","Mobile":"center center","Tablet":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain","Mobile":"cover"},"xposition":{"Desktop":{"point":"1","unit":"px"},"Mobile":{"point":"-500","unit":"px"},"Tablet":{"point":"-450","unit":"px"}},"width":{"Desktop":{"point":"1800","unit":"px"},"Mobile":{"unit":"px","point":"1200"}},"yposition":{"Mobile":{"point":"","unit":"px"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"mask":{"shape":"","svg":[],"size":{"Desktop":"custom"},"position":{"Desktop":"top right"},"repeat":{"Desktop":"no-repeat"},"scale":{"Desktop":{"unit":"%","point":"100"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-nLVg08","opacity":"","horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-lfDSBb","space":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Tablet":{"radius":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":null},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"positioningLocation":"absolute","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningTop":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"","unit":"px"}},"mask":{"shape":"custom","svg":{"id":61,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/masking.webp","width":800,"height":800,"altOriginal":"masking"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-white"}}} /-->

<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-kZZQPa","margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"","bottom":"100","left":""}},"Mobile":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-QofTu2","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}}} -->
<!-- wp:gutenverse/post-title {"elementId":"guten-LsiluZ","alignment":{"Tablet":"center","Desktop":"center","Mobile":"center"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"},"Tablet":{"point":"40","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"uppercase"},"color":{"type":"variable","id":"gv-color-text-primary"},"borderResponsive":{"Tablet":{"radius":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"1000","unit":"px"}}} -->
<div class="guten-element guten-post-title guten-LsiluZ animated guten-element-hide desktop-fadeInUp"></div>
<!-- /wp:gutenverse/post-title -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-1h5yZZ","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-q7dKAR","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Wf6uZq","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5","right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-mkDtAf"} -->
<!-- wp:gutenverse/icon {"elementId":"guten-1OzA7A","icon":"fas fa-user","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTIyNCAyNTZBMTI4IDEyOCAwIDEgMCAyMjQgMGExMjggMTI4IDAgMSAwIDAgMjU2em0tNDUuNyA0OEM3OS44IDMwNCAwIDM4My44IDAgNDgyLjNDMCA0OTguNyAxMy4zIDUxMiAyOS43IDUxMkg0MTguM2MxNi40IDAgMjkuNy0xMy4zIDI5LjctMjkuN0M0NDggMzgzLjggMzY4LjIgMzA0IDI2OS43IDMwNEgxNzguM3oiLz48L3N2Zz4=","iconAlign":{"Tablet":"center"},"ariaLabel":"author","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"},"Tablet":{"point":"","unit":"px"}},"iconPadding":{"Desktop":"0","Mobile":"","Tablet":"0"},"iconRotate":{"Tablet":""},"iconColorTwo":{"type":"variable","id":"gv-color-accent"},"iconShape":"circle","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"3","bottom":"-3"}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"1","right":"10","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-author {"elementId":"guten-Vz0U8S","authorAvatar":false,"typography":{"type":"variable","id":"gv-font-text-small","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"400"},"color":{"type":"variable","id":"gv-color-text-primary"},"authorBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-post-author guten-Vz0U8S"></div>
<!-- /wp:gutenverse/post-author -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-eh85QY","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"right":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}},"left":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}}},"borderResponsive":{"Mobile":{"radius":[],"left":{"type":"none"},"right":{"type":"none"}}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20","left":"20","top":"5","bottom":"5"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-uNFaO1","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-bsRfdF","icon":"fas fa-calendar-alt","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTEyOCAwYzE3LjcgMCAzMiAxNC4zIDMyIDMyVjY0SDI4OFYzMmMwLTE3LjcgMTQuMy0zMiAzMi0zMnMzMiAxNC4zIDMyIDMyVjY0aDQ4YzI2LjUgMCA0OCAyMS41IDQ4IDQ4djQ4SDBWMTEyQzAgODUuNSAyMS41IDY0IDQ4IDY0SDk2VjMyYzAtMTcuNyAxNC4zLTMyIDMyLTMyek0wIDE5Mkg0NDhWNDY0YzAgMjYuNS0yMS41IDQ4LTQ4IDQ4SDQ4Yy0yNi41IDAtNDgtMjEuNS00OC00OFYxOTJ6bTY0IDgwdjMyYzAgOC44IDcuMiAxNiAxNiAxNmgzMmM4LjggMCAxNi03LjIgMTYtMTZWMjcyYzAtOC44LTcuMi0xNi0xNi0xNkg4MGMtOC44IDAtMTYgNy4yLTE2IDE2em0xMjggMHYzMmMwIDguOCA3LjIgMTYgMTYgMTZoMzJjOC44IDAgMTYtNy4yIDE2LTE2VjI3MmMwLTguOC03LjItMTYtMTYtMTZIMjA4Yy04LjggMC0xNiA3LjItMTYgMTZ6bTE0NC0xNmMtOC44IDAtMTYgNy4yLTE2IDE2djMyYzAgOC44IDcuMiAxNiAxNiAxNmgzMmM4LjggMCAxNi03LjIgMTYtMTZWMjcyYzAtOC44LTcuMi0xNi0xNi0xNkgzMzZ6TTY0IDQwMHYzMmMwIDguOCA3LjIgMTYgMTYgMTZoMzJjOC44IDAgMTYtNy4yIDE2LTE2VjQwMGMwLTguOC03LjItMTYtMTYtMTZIODBjLTguOCAwLTE2IDcuMi0xNiAxNnptMTQ0LTE2Yy04LjggMC0xNiA3LjItMTYgMTZ2MzJjMCA4LjggNy4yIDE2IDE2IDE2aDMyYzguOCAwIDE2LTcuMiAxNi0xNlY0MDBjMC04LjgtNy4yLTE2LTE2LTE2SDIwOHptMTEyIDE2djMyYzAgOC44IDcuMiAxNiAxNiAxNmgzMmM4LjggMCAxNi03LjIgMTYtMTZWNDAwYzAtOC44LTcuMi0xNi0xNi0xNkgzMzZjLTguOCAwLTE2IDcuMi0xNiAxNnoiLz48L3N2Zz4=","iconAlign":{"Tablet":"center"},"ariaLabel":"date","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"},"Tablet":{"point":"","unit":"px"}},"iconPadding":{"Desktop":"0","Mobile":"","Tablet":"0"},"iconRotate":{"Tablet":""},"iconColorTwo":{"type":"variable","id":"gv-color-accent"},"iconShape":"circle","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"3","bottom":"-3"}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"1","right":"10","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-date {"elementId":"guten-oA83Zp","typography":{"type":"variable","id":"gv-font-text-small","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"400"},"color":{"type":"variable","id":"gv-color-text-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0"}},"Mobile":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-post-date guten-oA83Zp"></div>
<!-- /wp:gutenverse/post-date -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-XIyhay","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline","Mobile":"full"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-nfe4t1","horizontalAlign":{"Desktop":"default","Mobile":"center"}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-KZFeo3","icon":"fas fa-folder-open","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NzYgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTg4LjcgMjIzLjhMMCAzNzUuOFY5NkMwIDYwLjcgMjguNyAzMiA2NCAzMkgxODEuNWMxNyAwIDMzLjMgNi43IDQ1LjMgMTguN2wyNi41IDI2LjVjMTIgMTIgMjguMyAxOC43IDQ1LjMgMTguN0g0MTZjMzUuMyAwIDY0IDI4LjcgNjQgNjR2MzJIMTQ0Yy0yMi44IDAtNDMuOCAxMi4xLTU1LjMgMzEuOHptMjcuNiAxNi4xQzEyMi4xIDIzMCAxMzIuNiAyMjQgMTQ0IDIyNEg1NDRjMTEuNSAwIDIyIDYuMSAyNy43IDE2LjFzNS43IDIyLjItLjEgMzIuMWwtMTEyIDE5MkM0NTMuOSA0NzQgNDQzLjQgNDgwIDQzMiA0ODBIMzJjLTExLjUgMC0yMi02LjEtMjcuNy0xNi4xcy01LjctMjIuMiAuMS0zMi4xbDExMi0xOTJ6Ii8+PC9zdmc+","ariaLabel":"category","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0","Mobile":"0","Tablet":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-accent"},"iconShape":"circle","hideMobile":false,"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"3","bottom":"-3"}},"Tablet":{"unit":"px","dimension":{"top":"3","right":"10","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-terms {"elementId":"guten-PTuL6z","linkTo":"term","typography":{"type":"variable","id":"gv-font-text-small","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"400"},"color":{"type":"variable","id":"gv-color-text-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":""}}},"padding":{"Desktop":[]},"hideMobile":false,"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-post-terms guten-PTuL6z"></div>
<!-- /wp:gutenverse/post-terms -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/spacer {"elementId":"guten-Co4K5D","space":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":1},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"0","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}},"mask":{"shape":"custom","svg":{"id":62,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/masking-alt.webp","width":800,"height":800,"altOriginal":"masking alt"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-white"}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
