<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Contrax Home Gutenvese Hero', 'contrax-lite' ),
	'categories' => array( 'contrax-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-s5PTzQ","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-1"}},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="s5PTzQ"><section class="wp-block-gutenverse-section guten-element guten-section guten-s5PTzQ layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-czfc3s","mask":{"shape":""}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-czfc3s"><div class="guten-column-wrapper" data-id="czfc3s"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-K77eNm","background":{"videoPlayOnMobile":false,"type":"default","color":"","image":{"Desktop":{"id":31,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/sea-sunrise-vehicle-tower-resize.jpg"},"Tablet":{"id":124,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/sea-sunrise-vehicle-tower-tablet.webp"}},"position":{"Desktop":"bottom right","Mobile":"center left","Tablet":"top right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"},"xposition":{"Desktop":{"point":"1","unit":"px"},"Mobile":{"point":"-500","unit":"px"},"Tablet":{"point":"-450","unit":"px"}},"width":{"Desktop":{"point":"1800","unit":"px"},"Mobile":{"unit":"px","point":"1200"}},"yposition":{"Mobile":{"point":"","unit":"px"}}},"backgroundOverlay":{"type":"default","gradientColor":[{"color":"rgba(255, 255, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.045"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":2,"offset":"0.046"},{"color":"rgba(255, 255, 255, 0)","active":true,"opacity":0,"id":4,"offset":"0.954"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":3,"offset":"0.955"}],"gradientType":"linear","gradientAngle":"225"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"mask":{"shape":"","svg":[],"size":{"Desktop":"custom"},"position":{"Desktop":"top right"},"repeat":{"Desktop":"no-repeat"},"scale":{"Desktop":{"unit":"%","point":"100"}}}} -->
<div class="section-wrapper" data-id="K77eNm"><section class="wp-block-gutenverse-section guten-element guten-section guten-K77eNm layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-PWT9bl","opacity":"","horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"40","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-PWT9bl"><div class="guten-column-wrapper" data-id="PWT9bl"><!-- wp:gutenverse/spacer {"elementId":"guten-lfDSBb","space":{"Desktop":{"point":"120","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"50","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Tablet":{"radius":[]}},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"120","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"50","unit":"px"}},"positioningLocation":"absolute","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningTop":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"","unit":"px"}},"mask":{"shape":"custom","svg":{"id":41,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/masking.png"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"theme-1"}}} -->
<div class="guten-element guten-spacer guten-lfDSBb"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-qQ96Iw","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]},"zIndex":{"Desktop":2},"animation":{"type":{"Desktop":"fadeInRight"},"delay":100},"hideMobile":true,"positioningType":{"Desktop":"inline","Tablet":"inline"},"positioningWidth":{"Tablet":{"point":"216","unit":"px"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"positioningRight":{"Tablet":{"point":"125","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"330","unit":"px"}},"positioningTop":{"Mobile":{"point":"36","unit":"px"}},"positioningBottom":{"Desktop":{"point":"140","unit":"px"},"Tablet":{"point":"90","unit":"px"}}} -->
<div class="section-wrapper" data-id="qQ96Iw"><section class="wp-block-gutenverse-section guten-element guten-section guten-qQ96Iw animated guten-element-hide desktop-fadeInRight hide-mobile layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-bhtcRZ","verticalAlign":{"Desktop":"center","Tablet":"center"},"horizontalAlign":{"Desktop":"default","Tablet":"center"},"margin":{"Tablet":[]},"padding":{"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-bhtcRZ"><div class="guten-column-wrapper" data-id="bhtcRZ"><!-- wp:gutenverse/icon {"elementId":"guten-0u6bhp","icon":"gtn gtn-play","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"0","Tablet":0},"iconColorTwo":{"type":"variable","id":"theme-1"},"iconColorHoverTwo":{"type":"variable","id":"theme-9"},"iconShape":"circle","iconBorderWidth":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}},"iconBorderRadius":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}},"url":"#","animation":{"type":{"Desktop":"none"}},"background":{"type":"default","color":{"type":"variable","id":"theme-2"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":0,"color":{"r":0,"g":0,"b":0,"a":0}}},"borderHover":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"26","right":"24","bottom":"21","left":"28"}},"Tablet":{"unit":"px","dimension":{"top":"25","right":"23","bottom":"18","left":"26"}}},"zIndex":{"Desktop":2},"positioningType":{"Desktop":"inline"},"positioningLocation":"default","positioningLeft":{"Desktop":{"point":"","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Desktop":{"point":"","unit":"px"}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-0u6bhp guten-icon"><a class="guten-icon-wrapper circle stacked" href="#"><i class="gtn gtn-play"></i></a></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-B8cg6Z","textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"WdNgFq","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"400"},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"115","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-B8cg6Z"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Explore Our Video Projects</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-8rLu0Z","margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
<div class="section-wrapper" data-id="8rLu0Z"><section class="wp-block-gutenverse-section guten-element guten-section guten-8rLu0Z layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-dQLN3F","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-dQLN3F"><div class="guten-column-wrapper" data-id="dQLN3F"><!-- wp:gutenverse/spacer {"elementId":"guten-HeZnAJ","space":{"Desktop":{"point":"220","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"80","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"hideMobile":true} -->
<div class="guten-element guten-spacer guten-HeZnAJ hide-mobile"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-4F5n1P","animation":{"type":{"Desktop":"none"}}} -->
<div class="section-wrapper" data-id="4F5n1P"><section class="wp-block-gutenverse-section guten-element guten-section guten-4F5n1P layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-jWiHEG"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-jWiHEG"><div class="guten-column-wrapper" data-id="jWiHEG"><!-- wp:gutenverse/heading {"elementId":"guten-ITo6BR","type":1,"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"8AwtEC","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"75","unit":"px"},"Tablet":{"point":"56","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","right":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"40"}}},"animation":{"type":{"Desktop":"none"}}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-ITo6BR">Elevated Building</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/animated-text {"elementId":"guten-k2GWcG","titleTag":"h1","style":"flip","text":"Solutions Hub","loop":false,"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"PXEJFk","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"75","unit":"px"},"Tablet":{"point":"56","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500","transform":"uppercase"},"height":{"Desktop":{"point":"","unit":"px"}},"verticalAlign":{"Desktop":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":""}}},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"point":"210","unit":"px"}}} -->
<div class="guten-element guten-animated-text guten-k2GWcG style-flip" data-animation="flip" data-loop="false"><h1 class="text-content"><span class="text-wrapper"><span class="letters">Solutions Hub</span></span></h1></div>
<!-- /wp:gutenverse/animated-text -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-5qXpFF","textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"k9LI1q","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"animation":{"type":{"Desktop":"none"},"delay":null},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"590","unit":"px"},"Tablet":{"point":"430","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-5qXpFF"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Your hub for innovative and efficient building solutions, offering services from planning to execution and sustainability.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-FdM0nC","margin":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"delay":null}} -->
<div class="section-wrapper" data-id="FdM0nC"><section class="wp-block-gutenverse-section guten-element guten-section guten-FdM0nC layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-LDCfh8","verticalAlign":{"Desktop":"default","Mobile":"default"},"horizontalAlign":{"Desktop":"flex-start","Mobile":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-LDCfh8"><div class="guten-column-wrapper" data-id="LDCfh8"><!-- wp:gutenverse/button {"elementId":"guten-diPzvD","content":"Get In touch","url":"#","buttonWidth":{"Desktop":"","Mobile":""},"buttonHeight":{"Desktop":"60","Mobile":"55"},"alignButton":{"Desktop":"left","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"30","bottom":"16","left":"30"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"left":"28","right":"28","top":"0","bottom":"0"}}},"buttonBackground":{"type":"gradient","color":{"r":0,"g":0,"b":0,"a":0},"gradientColor":[{"color":"rgba(252, 96, 46, 0)","active":true,"opacity":0,"id":4,"offset":"0.081"},{"color":"rgba(252, 96, 46, 1)","active":false,"opacity":1,"id":1,"offset":"0.083"},{"color":"rgba(252, 96, 46, 1)","active":false,"opacity":1,"id":2,"offset":"0.919"},{"color":"rgba(252, 96, 46, 0)","active":false,"opacity":0,"id":3,"offset":"0.921"}],"gradientType":"linear","gradientAngle":"225"},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"buttonBorderHover":{"radius":{"Desktop":[]}},"icon":"gtn gtn-arrow-up-right-line","iconPosition":"after","iconSpacing":{"Desktop":"6"},"iconSize":{"Desktop":{"point":"30","unit":"px"}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"5"}}},"animation":{"type":{"Desktop":"fadeInLeft"}},"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"mVv5iG","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500","transform":"uppercase"},"hoverIconColor":{"type":"variable","id":"YtUvEX"},"hoverTextColor":{"type":"variable","id":"theme-9"},"positioningType":{"Desktop":"inline","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"259","unit":"px"},"Mobile":{"unit":"%","point":"50"}}} -->
<div class="guten-element guten-button-wrapper guten-diPzvD"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Get In touch</span></a></div>
<!-- /wp:gutenverse/button -->

<!-- wp:gutenverse/button {"elementId":"guten-OJBkLR","content":"Lern more","url":"#","buttonWidth":{"Desktop":"","Mobile":""},"buttonHeight":{"Desktop":"60","Mobile":"55"},"alignButton":{"Desktop":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"30","bottom":"16","left":"30"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"28","left":"28"}}},"buttonBackground":{"type":"gradient","color":{"r":0,"g":0,"b":0,"a":0},"gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":4,"offset":"0.080"},{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.082"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"0.915"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":3,"offset":"0.916"}],"gradientType":"linear","gradientAngle":"225"},"buttonBackgroundHover":{"type":"gradient"},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"buttonBorderHover":{"radius":{"Desktop":[]}},"icon":"gtn gtn-arrow-down-right-line","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"29","unit":"px"}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"delay":200},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"mVv5iG","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500","transform":"uppercase"},"hoverTextColor":{"type":"variable","id":"theme-2"},"positioningType":{"Desktop":"inline","Mobile":"default"},"positioningWidth":{"Mobile":{"unit":"%","point":"50"}}} -->
<div class="guten-element guten-button-wrapper guten-OJBkLR"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Lern more</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/spacer {"elementId":"guten-d4dAHh","space":{"Desktop":{"point":"220","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"80","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"margin":{"Mobile":[]},"padding":{"Mobile":[]},"hideMobile":true} -->
<div class="guten-element guten-spacer guten-d4dAHh hide-mobile"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/spacer {"elementId":"guten-Co4K5D","space":{"Desktop":{"point":"120","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"50","unit":"px"}},"border":{"radius":{"Desktop":[]}},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"120","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"50","unit":"px"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"0","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}},"mask":{"shape":"custom","svg":{"id":43,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/masking-alt.png"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"theme-1"}}} -->
<div class="guten-element guten-spacer guten-Co4K5D"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
