<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Contrax Gutenvese Funfact', 'contrax-lite' ),
	'categories' => array( 'contrax-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1290},"elementId":"guten-Yg2ExO","background":{"videoPlayOnMobile":false,"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"blendMode":{"Desktop":"normal"},"color":{"type":"variable","id":"theme-1"}},"opacity":"0.9","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"150","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"right":"0","top":"80","bottom":"80","left":"0"}}}} -->
<div class="section-wrapper" data-id="Yg2ExO"><section class="wp-block-gutenverse-section guten-element guten-section guten-Yg2ExO layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-rp4fMa","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-rp4fMa"><div class="guten-column-wrapper" data-id="rp4fMa"><!-- wp:gutenverse/section {"width":{"Desktop":"1280"},"isChild":true,"gap":"no","elementId":"guten-psTd9j"} -->
<div class="section-wrapper" data-id="psTd9j"><section class="wp-block-gutenverse-section guten-element guten-section guten-psTd9j layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":50},"elementId":"guten-eQA4Am","verticalAlign":{"Desktop":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"0","bottom":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-eQA4Am"><div class="guten-column-wrapper" data-id="eQA4Am"><!-- wp:gutenverse/fun-fact {"elementId":"guten-V0ma9C","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":""},"iconPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"prefix":"","number":"275","suffix":"","title":"Awwards Winning","showSupper":true,"superColor":{"type":"variable","id":"theme-2"},"superTypography":{"type":"variable","id":"WXSRLk","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"superTop":{"Desktop":"-8","Mobile":"-5"},"superSpace":{"Desktop":"-5","Mobile":"0"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"center","Tablet":"center"},"numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-3"}},"numberTypography":{"type":"variable","id":"P4Hcoa","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"titleTypography":{"type":"variable","id":"saq537","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"400"},"numberBottomSpace":{"Desktop":"8","Mobile":"4","Tablet":"6"},"titleBottomSpace":{"Mobile":"","Desktop":""},"numberRightSpace":{"Mobile":"","Desktop":"-4"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"margin":{"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":[],"Tablet":[]}} -->
<div class="guten-element guten-V0ma9C guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="275" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Awwards Winning</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":50},"elementId":"guten-RWMnrD","verticalAlign":{"Desktop":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","right":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"","right":"0","bottom":"40"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0","bottom":"40","top":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-RWMnrD"><div class="guten-column-wrapper" data-id="RWMnrD"><!-- wp:gutenverse/fun-fact {"elementId":"guten-1PORBm","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"iconSize":{"Desktop":""},"iconPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"prefix":"","number":"98","suffix":"","title":"Completion Rate","showSupper":true,"supper":"%","superColor":{"type":"variable","id":"theme-2"},"superTypography":{"type":"variable","id":"WXSRLk","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"superTop":{"Desktop":"0","Mobile":""},"superSpace":{"Desktop":"-5","Mobile":"0"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"center","Tablet":"center"},"numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-3"}},"numberTypography":{"type":"variable","id":"P4Hcoa","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"titleTypography":{"type":"variable","id":"saq537","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"400"},"numberBottomSpace":{"Desktop":"8","Mobile":"4","Tablet":"6"},"titleBottomSpace":{"Mobile":"","Desktop":""},"numberRightSpace":{"Desktop":"-4"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"margin":{"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":[],"Tablet":[]}} -->
<div class="guten-element guten-1PORBm guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="98" data-duration="3500"></span><span class="suffix"></span><sup class="super">%</sup></div><span class="title">Completion Rate</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":50},"elementId":"guten-7mEIS5","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-7mEIS5"><div class="guten-column-wrapper" data-id="7mEIS5"><!-- wp:gutenverse/fun-fact {"elementId":"guten-oxUx5M","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"iconSize":{"Desktop":""},"iconPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"prefix":"","number":"125","suffix":"","title":"Project Finished","showSupper":true,"superColor":{"type":"variable","id":"theme-2"},"superTypography":{"type":"variable","id":"WXSRLk","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"superTop":{"Desktop":"-8","Mobile":"-5"},"superSpace":{"Desktop":"-5","Mobile":"0"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"center","Tablet":"center"},"numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-3"}},"numberTypography":{"type":"variable","id":"P4Hcoa","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"titleTypography":{"type":"variable","id":"saq537","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"400"},"numberBottomSpace":{"Desktop":"8","Mobile":"4","Tablet":"6"},"titleBottomSpace":{"Mobile":"","Desktop":""},"numberRightSpace":{"Mobile":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"point":"","unit":"px"}}} -->
<div class="guten-element guten-oxUx5M guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="125" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Project Finished</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":50},"elementId":"guten-dNCuuf","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-dNCuuf"><div class="guten-column-wrapper" data-id="dNCuuf"><!-- wp:gutenverse/fun-fact {"elementId":"guten-rGuQY7","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"iconSize":{"Desktop":""},"iconPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"prefix":"","number":"95","suffix":"","title":"Happy Customers","showSupper":true,"superColor":{"type":"variable","id":"theme-2"},"superTypography":{"type":"variable","id":"WXSRLk","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"superTop":{"Desktop":"-8","Mobile":"-5"},"superSpace":{"Desktop":"-5","Mobile":"0"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"center","Tablet":"center"},"numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-3"}},"numberTypography":{"type":"variable","id":"P4Hcoa","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"54","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"titleTypography":{"type":"variable","id":"saq537","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"400"},"numberBottomSpace":{"Desktop":"8","Mobile":"4","Tablet":"6"},"titleBottomSpace":{"Mobile":"","Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"margin":{"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"point":"","unit":"px"}}} -->
<div class="guten-element guten-rGuQY7 guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="95" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Happy Customers</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
