<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Contrax About Gutenvese Hero', 'contrax-lite' ),
	'categories' => array( 'contrax-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1290"},"gap":"no","elementId":"guten-K77eNm","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":235,"g":235,"b":235,"a":1},"image":{"Desktop":[],"Tablet":[]},"position":{"Desktop":"center right","Mobile":"center center","Tablet":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain","Mobile":"cover"},"xposition":{"Desktop":{"point":"1","unit":"px"},"Mobile":{"point":"-500","unit":"px"},"Tablet":{"point":"-450","unit":"px"}},"width":{"Desktop":{"point":"1800","unit":"px"},"Mobile":{"unit":"px","point":"1200"}},"yposition":{"Mobile":{"point":"","unit":"px"}}},"backgroundOverlay":{"type":"default","gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":6,"offset":"0.048"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":5,"offset":"0.049"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":4,"offset":"0.951"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"0.951"}],"gradientType":"linear","gradientAngle":"225"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40","top":"","bottom":"140"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"100","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"100","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"mask":{"shape":"","svg":[],"size":{"Desktop":"custom"},"position":{"Desktop":"top right"},"repeat":{"Desktop":"no-repeat"},"scale":{"Desktop":{"unit":"%","point":"100"}}}} -->
<div class="section-wrapper" data-id="K77eNm"><section class="wp-block-gutenverse-section guten-element guten-section guten-K77eNm layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-PWT9bl","opacity":"","horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"80","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-PWT9bl"><div class="guten-column-wrapper" data-id="PWT9bl"><!-- wp:gutenverse/spacer {"elementId":"guten-lfDSBb","space":{"Desktop":{"point":"110","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Tablet":{"radius":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":null},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"110","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"positioningLocation":"absolute","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningTop":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"","unit":"px"}},"mask":{"shape":"custom","svg":{"id":61,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/masking.png"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"theme-1"}}} -->
<div class="guten-element guten-spacer guten-lfDSBb"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-8rLu0Z","margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"40"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"","bottom":"40","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}}} -->
<div class="section-wrapper" data-id="8rLu0Z"><section class="wp-block-gutenverse-section guten-element guten-section guten-8rLu0Z layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":68,"Tablet":100,"Mobile":null},"elementId":"guten-dQLN3F","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-dQLN3F"><div class="guten-column-wrapper" data-id="dQLN3F"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Bgmsxy","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"24"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"}}} -->
<div class="section-wrapper" data-id="Bgmsxy"><section class="wp-block-gutenverse-section guten-element guten-section guten-Bgmsxy animated guten-element-hide desktop-fadeInLeft layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-Bf5lVJ","verticalAlign":{"Desktop":"default","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Bf5lVJ"><div class="guten-column-wrapper" data-id="Bf5lVJ"><!-- wp:gutenverse/divider {"elementId":"guten-BXAbG3","width":{"Desktop":"100","Mobile":""},"dividerColor":{"type":"variable","id":"theme-2"},"size":{"Desktop":"1"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Mobile":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"70","unit":"px"},"Mobile":{"point":"50","unit":"px"},"Tablet":{"point":"60","unit":"px"}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-BXAbG3"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/heading {"elementId":"guten-8EZHCp","type":6,"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"n1CZUD","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"point":"151","unit":"px"}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-8EZHCp"><strong>Who We Are</strong></h6>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-ITo6BR","type":1,"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"rLQXwY","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"50","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","right":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"40"}}},"animation":{"type":{"Desktop":"none"}}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-ITo6BR">Turning Concepts</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/animated-text {"elementId":"guten-k2GWcG","titleTag":"h1","style":"flip","text":"into Concrete","loop":false,"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"7BXnGM","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Tablet":{"point":"50","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"uppercase"},"height":{"Desktop":{"point":"","unit":"px"}},"verticalAlign":{"Desktop":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":""}}},"positioningType":{"Mobile":"default"},"positioningWidth":{"Mobile":{"point":"210","unit":"px"}}} -->
<div class="guten-element guten-animated-text guten-k2GWcG style-flip" data-animation="flip" data-loop="false"><h1 class="text-content"><span class="text-wrapper"><span class="letters">into Concrete</span></span></h1></div>
<!-- /wp:gutenverse/animated-text --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":32,"Tablet":100,"Mobile":null},"elementId":"guten-tZTb2Q","verticalAlign":{"Desktop":"flex-end"},"horizontalAlign":{"Desktop":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"10"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"10","bottom":"20","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-tZTb2Q"><div class="guten-column-wrapper" data-id="tZTb2Q"><!-- wp:gutenverse/text-editor {"elementId":"guten-d7F5jd","textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"k9LI1q","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"590","unit":"px"},"Tablet":{"point":"500","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-d7F5jd"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":1290},"isChild":true,"elementId":"guten-7Hc4ph","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"-150","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-100","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"-100","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":[]},"zIndex":{"Desktop":2},"positioningLocation":"default","positioningBottom":{"Desktop":{"point":"-150","unit":"px"},"Tablet":{"point":"-120","unit":"px"},"Mobile":{"point":"-449","unit":"px"}}} -->
<div class="section-wrapper" data-id="7Hc4ph"><section class="wp-block-gutenverse-section guten-element guten-section guten-7Hc4ph layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":68,"Tablet":null},"elementId":"guten-seRyML","background":{"type":"default","image":{"Desktop":{"id":181,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/sea-dock-air-building-ship-transport.jpg"}},"position":{"Desktop":"bottom center"},"color":{"r":0,"g":0,"b":0,"a":1},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-seRyML"><div class="guten-column-wrapper" data-id="seRyML"><!-- wp:gutenverse/spacer {"elementId":"guten-JQhjkR","space":{"Desktop":{"point":"300","unit":"px"},"Tablet":{"point":"220","unit":"px"},"Mobile":{"point":"200","unit":"px"}},"borderResponsive":{"Mobile":{"radius":[]}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="guten-element guten-spacer guten-JQhjkR"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":32,"Tablet":null,"Mobile":null},"elementId":"guten-DblOqU","background":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1},"image":{"Desktop":{"id":180,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/construction-workers.jpg"}},"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"},"position":{"Desktop":"bottom right"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DblOqU"><div class="guten-column-wrapper" data-id="DblOqU"><!-- wp:gutenverse/spacer {"elementId":"guten-PNip8r","space":{"Desktop":{"point":"300","unit":"px"},"Mobile":{"point":"181","unit":"px"},"Tablet":{"point":"220","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-PNip8r"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/spacer {"elementId":"guten-Co4K5D","space":{"Desktop":{"point":"110","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":1},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"110","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"0","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}},"mask":{"shape":"custom","svg":{"id":62,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/masking-alt.png"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"theme-1"}}} -->
<div class="guten-element guten-spacer guten-Co4K5D"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
