<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Contrax Home Gutenvese Process', 'contrax-lite' ),
	'categories' => array( 'contrax-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1290},"elementId":"guten-SyBlN9","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"10","bottom":"","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"80","right":"10","bottom":"0","left":"10"}}}} -->
<div class="section-wrapper" data-id="SyBlN9"><section class="wp-block-gutenverse-section guten-element guten-section guten-SyBlN9 layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-V51BWP","horizontalAlign":{"Desktop":"center"},"margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-V51BWP"><div class="guten-column-wrapper" data-id="V51BWP"><!-- wp:gutenverse/section {"width":{"Desktop":"733"},"isChild":true,"gap":"no","elementId":"guten-gagQJl","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":[]}} -->
<div class="section-wrapper" data-id="gagQJl"><section class="wp-block-gutenverse-section guten-element guten-section guten-gagQJl layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-KKF7yA","horizontalAlign":{"Desktop":"center","Tablet":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-KKF7yA"><div class="guten-column-wrapper" data-id="KKF7yA"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-QiJRgh","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"24"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"animation":{"type":{"Desktop":"fadeInUp"}}} -->
<div class="section-wrapper" data-id="QiJRgh"><section class="wp-block-gutenverse-section guten-element guten-section guten-QiJRgh animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-r5tqks","verticalAlign":{"Desktop":"default","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Mobile":"center","Tablet":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-r5tqks"><div class="guten-column-wrapper" data-id="r5tqks"><!-- wp:gutenverse/divider {"elementId":"guten-yqhfp1","width":{"Desktop":"100","Mobile":""},"dividerColor":{"type":"variable","id":"theme-2"},"size":{"Desktop":"1"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Mobile":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"70","unit":"px"},"Mobile":{"point":"50","unit":"px"},"Tablet":{"point":"60","unit":"px"}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-yqhfp1"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/heading {"elementId":"guten-MUxYJE","type":6,"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"n1CZUD","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"point":"151","unit":"px"}}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-MUxYJE">Process</h6>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/divider {"elementId":"guten-DDoX3G","width":{"Desktop":"100","Mobile":""},"dividerColor":{"type":"variable","id":"theme-2"},"size":{"Desktop":"1"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Mobile":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"70","unit":"px"},"Mobile":{"point":"50","unit":"px"},"Tablet":{"point":"60","unit":"px"}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-DDoX3G"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-UuH8AO","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"iIJ9h6","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"},"Tablet":{"point":"40","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInDown"},"delay":200},"positioningType":{"Desktop":"full","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"550","unit":"px"},"Tablet":{"point":"570","unit":"px"},"Mobile":{"point":"250","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-UuH8AO animated guten-element-hide desktop-fadeInDown"><strong><strong><strong><strong>Our Work Process</strong></strong></strong></strong></h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-c6ru9n","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"k9LI1q","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Tablet":[],"Desktop":[]},"padding":{"Tablet":[],"Desktop":[]},"animation":{"type":{"Desktop":"fadeInDown"},"delay":100},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"599","unit":"px"},"Tablet":{"point":"455","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-c6ru9n animated guten-element-hide desktop-fadeInDown"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Tune into our comprehensive framework outlining our methodical approach to project management for successful outcomes.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-5NZPcV","margin":{"Desktop":{"unit":"px","dimension":{"top":"80"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="section-wrapper" data-id="5NZPcV"><section class="wp-block-gutenverse-section guten-element guten-section guten-5NZPcV layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-wOyI9u","order":{"Tablet":2},"verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"top":"40","left":"0","right":"0"}}},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-wOyI9u"><div class="guten-column-wrapper" data-id="wOyI9u"><!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-IEoREu","margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"480","unit":"px"}}} -->
<div class="section-wrapper" data-id="IEoREu"><section class="wp-block-gutenverse-section guten-element guten-section guten-IEoREu layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-mTzBSF","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-mTzBSF"><div class="guten-column-wrapper" data-id="mTzBSF"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-4dwCOF","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Tablet":"custom","Mobile":"full"},"positioningWidth":{"Tablet":{"unit":"%","point":"33.3"}}} -->
<div class="section-wrapper" data-id="4dwCOF"><section class="wp-block-gutenverse-section guten-element guten-section guten-4dwCOF layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":100},"elementId":"guten-c3ykV1","background":{"type":"gradient","color":{"r":235,"g":235,"b":235,"a":1},"gradientColor":[{"color":"rgba(235, 235, 235, 0)","active":false,"opacity":0,"id":4,"offset":"0.067"},{"color":"rgba(235, 235, 235, 1)","opacity":1,"active":true,"id":1,"offset":"0.069"},{"color":"rgba(235, 235, 235, 1)","active":false,"opacity":1,"id":2,"offset":"0.924"},{"color":"rgba(235, 235, 235, 0)","active":false,"opacity":0,"id":3,"offset":"0.926"}],"gradientType":"linear","gradientAngle":"45"},"opacity":"1","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"24","right":"30","bottom":"24","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"40","left":"30"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-c3ykV1"><div class="guten-column-wrapper" data-id="c3ykV1"><!-- wp:gutenverse/heading {"elementId":"guten-hF6ZQ4","color":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"oe0Bpc","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"45","unit":"px"},"Tablet":{"point":"45","unit":"px"},"Mobile":{"point":"45","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"700"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"90","unit":"px"}},"positioningLocation":"default","positioningTop":{"Desktop":{"point":"0","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-hF6ZQ4">01</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-b7BaZC","separateButtonLink":false,"title":"\u003cstrong\u003eConsultation\u003c/strong\u003e","titleTag":"h3","description":"Directly understand client\'s project needs and goals comprehensively.","iconType":"none","iconSize":{"Desktop":"0"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none","width":0}},"containerBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"HEGRJG","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-3"},"descTypography":{"type":"variable","id":"8byQMN","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"300"},"badgePadding":{"Desktop":[],"Tablet":[]},"badgeMargin":{"Desktop":[],"Tablet":[]},"badgeRadius":{"Desktop":[],"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"320","unit":"px"}},"parentSelector":".guten-b7BaZC:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-b7BaZC guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title"><strong>Consultation</strong></h3><p class="icon-box-description">Directly understand client\'s project needs and goals comprehensively.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-ZlOGdJ","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"left":"10","right":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Tablet":"custom","Mobile":"full"},"positioningWidth":{"Tablet":{"unit":"%","point":"33.3"}}} -->
<div class="section-wrapper" data-id="ZlOGdJ"><section class="wp-block-gutenverse-section guten-element guten-section guten-ZlOGdJ layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-31QHfv","backgroundHover":{"type":"gradient","gradientColor":[{"color":"rgba(235, 235, 235, 0)","active":true,"opacity":0,"id":4,"offset":"0.068"},{"color":"rgba(235, 235, 235, 1)","active":false,"id":3,"offset":"0.069"},{"color":"rgba(235, 235, 235, 1)","opacity":1,"active":false,"id":1,"offset":"0.924"},{"color":"rgba(235, 235, 235, 0)","active":false,"opacity":0,"id":2,"offset":"0.926"}],"gradientType":"linear","gradientAngle":"45"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"24","right":"30","bottom":"24","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"40","left":"30"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-31QHfv"><div class="guten-column-wrapper" data-id="31QHfv"><!-- wp:gutenverse/heading {"elementId":"guten-OfiSQu","color":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"oe0Bpc","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"45","unit":"px"},"Tablet":{"point":"45","unit":"px"},"Mobile":{"point":"45","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"700"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"90","unit":"px"}},"positioningLocation":"default","positioningTop":{"Desktop":{"point":"0","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-OfiSQu">02</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-8MVaNQ","separateButtonLink":false,"title":"\u003cstrong\u003ePlanning and Design\u003c/strong\u003e","titleTag":"h3","description":"Meticulously tailoring project plans to perfectly fit client preferences.","iconType":"none","iconSize":{"Desktop":"0"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none","width":0}},"containerBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"HEGRJG","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-3"},"descTypography":{"type":"variable","id":"8byQMN","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"300"},"badgePadding":{"Desktop":[],"Tablet":[]},"badgeMargin":{"Desktop":[],"Tablet":[]},"badgeRadius":{"Desktop":[],"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","left":""}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"320","unit":"px"}},"parentSelector":".guten-8MVaNQ:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-8MVaNQ guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title"><strong>Planning and Design</strong></h3><p class="icon-box-description">Meticulously tailoring project plans to perfectly fit client preferences.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-3arWbn","backgroundHover":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Tablet":"custom","Mobile":"full"},"positioningWidth":{"Tablet":{"unit":"%","point":"33.3"}}} -->
<div class="section-wrapper" data-id="3arWbn"><section class="wp-block-gutenverse-section guten-element guten-section guten-3arWbn layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-HoiSEk","backgroundHover":{"type":"gradient","gradientColor":[{"color":"rgba(235, 235, 235, 0)","active":false,"opacity":0,"id":4,"offset":"0.071"},{"color":"rgba(235, 235, 235, 1)","active":true,"id":3,"offset":"0.073"},{"color":"rgba(235, 235, 235, 1)","opacity":1,"active":false,"id":1,"offset":"0.922"},{"color":"rgba(235, 235, 235, 0)","active":false,"opacity":0,"id":2,"offset":"0.925"}],"gradientType":"linear","gradientAngle":"45"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"24","right":"30","bottom":"24","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"40","left":"30"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-HoiSEk"><div class="guten-column-wrapper" data-id="HoiSEk"><!-- wp:gutenverse/heading {"elementId":"guten-ywMXpg","color":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"oe0Bpc","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"45","unit":"px"},"Tablet":{"point":"45","unit":"px"},"Mobile":{"point":"45","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"700"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"90","unit":"px"}},"positioningLocation":"default","positioningTop":{"Desktop":{"point":"0","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-ywMXpg">03</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-6YuFkl","separateButtonLink":false,"title":"\u003cstrong\u003e\u003cstrong\u003eExecution and Review\u003c/strong\u003e\u003c/strong\u003e","titleTag":"h3","description":"Implementing the project, conducting periodic reviews for adjustments.","iconType":"none","iconSize":{"Desktop":"0"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none","width":0}},"containerBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"HEGRJG","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-3"},"descTypography":{"type":"variable","id":"8byQMN","font":{"label":"Almarai","value":"Almarai","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"300"},"badgePadding":{"Desktop":[],"Tablet":[]},"badgeMargin":{"Desktop":[],"Tablet":[]},"badgeRadius":{"Desktop":[],"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","left":""}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"320","unit":"px"}},"parentSelector":".guten-6YuFkl:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-6YuFkl guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title"><strong><strong>Execution and Review</strong></strong></h3><p class="icon-box-description">Implementing the project, conducting periodic reviews for adjustments.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-vXWNrF","background":{"type":"default","image":{"Desktop":{"id":98,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/man-wood-roof-building-beam-steel.jpg"}},"size":{"Desktop":"cover"},"position":{"Desktop":"bottom center","Tablet":"center center"},"repeat":{"Desktop":"no-repeat"}},"backgroundOverlay":{"type":"default","gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":1,"offset":"0.064"},{"color":"rgba(255, 255, 255, 0)","active":true,"opacity":0,"id":3,"offset":"0.066"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":4,"offset":"0.921"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"0.922"}],"gradientType":"linear","gradientAngle":"225"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"mask":{"shape":"","svg":{"id":396,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/shape-mask-2.png"},"size":{"Desktop":"cover"},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vXWNrF"><div class="guten-column-wrapper" data-id="vXWNrF"><div class="guten-background-overlay"></div><!-- wp:gutenverse/spacer {"elementId":"guten-W80mOa","space":{"Desktop":{"point":"481","unit":"px"},"Tablet":{"point":"440","unit":"px"},"Mobile":{"point":"240","unit":"px"}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-spacer guten-W80mOa"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/icon {"elementId":"guten-Uk3ZZq","icon":"gtn gtn-play","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"0","Tablet":""},"iconColorTwo":{"type":"variable","id":"theme-1"},"iconColorHoverTwo":{"type":"variable","id":"theme-9"},"iconShape":"circle","iconBorderWidth":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}},"iconBorderRadius":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}},"url":"#","animation":{"type":{"Desktop":"none"}},"background":{"type":"default","color":{"type":"variable","id":"theme-2"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":0,"color":{"r":0,"g":0,"b":0,"a":0}}},"borderHover":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"26","right":"24","bottom":"21","left":"28"}},"Tablet":{"unit":"px","dimension":{"top":"27","right":"24","bottom":"20","left":"28"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"18","bottom":"14","left":"22"}}},"zIndex":{"Desktop":2},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"","unit":"px"}},"positioningRight":{"Desktop":{"point":"8","unit":"px"},"Mobile":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"22","unit":"px"},"Mobile":{"point":"15","unit":"px"}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-Uk3ZZq guten-icon"><a class="guten-icon-wrapper circle stacked" href="#"><i class="gtn gtn-play"></i></a></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/spacer {"elementId":"guten-1EWrRZ","space":{"Desktop":{"point":"100","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"50","unit":"px"}},"border":{"radius":{"Desktop":[]}},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"100","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"50","unit":"px"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"0","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Desktop":{"point":"0","unit":"px"}},"mask":{"shape":"custom","svg":{"id":62,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/masking-alt.png"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"theme-1"}}} -->
<div class="guten-element guten-spacer guten-1EWrRZ"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/spacer {"elementId":"guten-i5Fmh4","space":{"Desktop":{"point":"100","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"50","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Tablet":{"radius":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":null},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"100","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"50","unit":"px"}},"positioningLocation":"absolute","positioningRight":{"Desktop":{"point":"0","unit":"px"}},"positioningTop":{"Desktop":{"point":"0","unit":"px"}},"positioningBottom":{"Desktop":{"point":"","unit":"px"}},"mask":{"shape":"custom","svg":{"id":61,"image":"' . esc_url( CONTRAX_LITE_URI ) . 'assets/img/masking.png"},"size":{"Desktop":"cover"},"position":{"Desktop":"top right"}},"background":{"type":"default","color":{"type":"variable","id":"theme-1"}}} -->
<div class="guten-element guten-spacer guten-i5Fmh4"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
